using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ESSONS_MIS_2020.Models
{
    public class QuyTrinhModel
    {
        public string SoDonKhuon { get; set; }
        public string NgayDuyet { get; set; }
        public string PhienBan1 { get; set; }
        public string NgayPhatHanh1 { get; set; }
        public string PhienBan2 { get; set; }
        public string NgayPhatHanh2 { get; set; }
        public string PhienBan3 { get; set; }
        public string NgayPhatHanh3 { get; set; }
        public string PhienBan4 { get; set; }
        public string NgayPhatHanh4 { get; set; }
        public int SoLoKhuonKH { get; set; }
        public string CoRutTheoDonKhuon { get; set; }
        public string UocTinhKLSP { get; set; }
        public string ThoiGianHoanTat1k { get; set; }
        public string LoaiKhuonMau { get; set; }
        public string CodeKH { get; set; }
        public string CodeSP { get; set; }
        public string TenQU { get; set; }
        public string MaKhuonTW { get; set; }
        public string QuyCachKH { get; set; }
        public string QuyCachEssons { get; set; }
        public string ChatKeo { get; set; }
        public string Mau { get; set; }
        public string MaKeo1 { get; set; }
        public string MaKeo2 { get; set; }
        public string PantoneMau { get; set; }
        public string GhiChuKHSX { get; set; }
        public string GocNL { get; set; }
        public int SoPCSMoiBo { get; set; }
        public string PhaKeo { get; set; }
        public string NgayGiaoMau { get; set; }
        public string NgayKHApprovedMau { get; set; }
        public string NgayPheDuyetMua { get; set; }
        public string MaKeoKho1 { get; set; }
        public string HoaChat1MK1 { get; set; }
        public string KhoiLuongHC1MK1 { get; set; }
        public string HoaChat2MK1 { get; set; }
        public string KhoiLuongHC2MK1 { get; set; }
        public string HoaChat3MK1 { get; set; }
        public string KhoiLuongHC3MK1 { get; set; }
        public string HoaChat4MK1 { get; set; }
        public string KhoiLuongHC4MK1 { get; set; }
        public string HoaChat5MK1 { get; set; }
        public string KhoiLuongHC5MK1 { get; set; }
        public string HoaChat6MK1 { get; set; }
        public string KhoiLuongHC6MK1 { get; set; }
        public string HoaChat7MK1 { get; set; }
        public string KhoiLuongHC7MK1 { get; set; }
        public string HoaChat1MK1KH { get; set; }
        public string KhoiLuongHC1MK1KH { get; set; }
        public string HoaChat2MK1KH { get; set; }
        public string KhoiLuongHC2MK1KH { get; set; }
        public string HoaChat3MK1KH { get; set; }
        public string KhoiLuongHC3MK1KH { get; set; }
        public string HoaChat4MK1KH { get; set; }
        public string KhoiLuongHC4MK1KH { get; set; }
        public string HoaChat5MK1KH { get; set; }
        public string KhoiLuongHC5MK1KH { get; set; }
        public string HoaChat6MK1KH { get; set; }
        public string KhoiLuongHC6MK1KH { get; set; }
        public string HoaChat7MK1KH { get; set; }
        public string KhoiLuongHC7MK1KH { get; set; }
        public string MaKeoKho2 { get; set; }
        public string HoaChat1MK2 { get; set; }
        public string KhoiLuongHC1MK2 { get; set; }
        public string HoaChat2MK2 { get; set; }
        public string KhoiLuongHC2MK2 { get; set; }
        public string HoaChat3MK2 { get; set; }
        public string KhoiLuongHC3MK2 { get; set; }
        public string HoaChat4MK2 { get; set; }
        public string KhoiLuongHC4MK2 { get; set; }
        public string HoaChat5MK2 { get; set; }
        public string KhoiLuongHC5MK2 { get; set; }
        public string HoaChat6MK2 { get; set; }
        public string KhoiLuongHC6MK2 { get; set; }
        public string HoaChat7MK2 { get; set; }
        public string KhoiLuongHC7MK2 { get; set; }
        public string HoaChat1MK2KH { get; set; }
        public string KhoiLuongHC1MK2KH { get; set; }
        public string HoaChat2MK2KH { get; set; }
        public string KhoiLuongHC2MK2KH { get; set; }
        public string HoaChat3MK2KH { get; set; }
        public string KhoiLuongHC3MK2KH { get; set; }
        public string HoaChat4MK2KH { get; set; }
        public string KhoiLuongHC4MK2KH { get; set; }
        public string HoaChat5MK2KH { get; set; }
        public string KhoiLuongHC5MK2KH { get; set; }
        public string HoaChat6MK2KH { get; set; }
        public string KhoiLuongHC6MK2KH { get; set; }
        public string HoaChat7MK2KH { get; set; }
        public string KhoiLuongHC7MK2KH { get; set; }
        public string NgayDuyetPhoiThep { get; set; }
        public string NgayMuaPhoiThep { get; set; }
        public string SoCTMuaPhoi { get; set; }
        public string NCCPhoiThep { get; set; }
        public string LoaiThepKhuon { get; set; }
        public string KichThuocKhuon { get; set; }
        public int SoTam { get; set; }
        public string CoRutThucTe { get; set; }
        public string LoaiKhuon { get; set; }
        public string PhuKienCTK { get; set; }
        public string PPXuLyBTP { get; set; }
        public string NgaySXKhuon { get; set; }
        public string NgayHoanThanhDuKien { get; set; }
        public string NgayHoanThanh { get; set; }
        public string SuaChiTietLan1 { get; set; }
        public string NgaySuaChiTietLan1 { get; set; }
        public string SuaChiTietLan2 { get; set; }
        public string NgaySuaChiTietLan2 { get; set; }
        public string SuaChiTietLan3 { get; set; }
        public string NgaySuaChiTietLan3 { get; set; }
        public string SuaChiTietLan4 { get; set; }
        public string NgaySuaChiTietLan4 { get; set; }
        public string NgayNhanKhuon { get; set; }
        public string ViTriKhuon { get; set; }
        public int SoKhuonHienCo { get; set; }
        public string ViTriPhuKien { get; set; }
        public string XuLyBeMat { get; set; }
        public string PPCheBienNL { get; set; }
        public int ThoiGianTron { get; set; }
        public int TongThoiGianCan { get; set; }
        public string ChiTietCaiTien { get; set; }
        public string PPCat { get; set; }
        public string DoDay { get; set; }
        public string ChieuDaiMin { get; set; }
        public string ChieuDaiMax { get; set; }
        public string TLSoiMin { get; set; }
        public string TLSoiMax { get; set; }
        public string SoSoi { get; set; }
        public string DoDay2 { get; set; }
        public string ChieuDaiMin2 { get; set; }
        public string ChieuDaiMax2 { get; set; }
        public string TLSoiMin2 { get; set; }
        public string TLSoiMax2 { get; set; }
        public string SoSoi2 { get; set; }
        public string DoDay3 { get; set; }
        public string ChieuDaiMin3 { get; set; }
        public string ChieuDaiMax3 { get; set; }
        public string TLSoiMin3 { get; set; }
        public string TLSoiMax3 { get; set; }
        public string SoSoi3 { get; set; }
        public string DoDay4 { get; set; }
        public string ChieuDaiMin4 { get; set; }
        public string ChieuDaiMax4 { get; set; }
        public string TLSoiMin4 { get; set; }
        public string TLSoiMax4 { get; set; }
        public string SoSoi4 { get; set; }
        public string PPDatKeo { get; set; }
        public string TheTichBom { get; set; }
        public string CachDat { get; set; }
        public int SoLoKhuon { get; set; }
        public int SoLoThucLam { get; set; }
        public int Tren5 { get; set; }
        public int Duoi5 { get; set; }
        public int LucEp { get; set; }
        public int SoLanThoatKhi { get; set; }
        public string TongTLSat { get; set; }
        public string KLSPThucTe { get; set; }
        public string ThoiGianLuuHoa { get; set; }
        public string ThoiGianHoanTat { get; set; }
        public string ChatLuong { get; set; }
        public string XuLyDinhDH { get; set; }
        public string XuLyBTPTaiDH { get; set; }
        public string DCBocTay { get; set; }
        public string DCXuLyBeMat { get; set; }
        public string NgayKTMau { get; set; }
        public string KTTruocLH { get; set; }
        public string KTSauLH { get; set; }
        public string KTXuatMau { get; set; }
        public string PPBocTachBTM { get; set; }
        public string XuLyBeMatBTM { get; set; }
        public string ThoiGian { get; set; }
        public string TocDo { get; set; }
        public string KL1LanBan { get; set; }
        public string LoaiCatBi { get; set; }
        public string NhietDo { get; set; }
        public string ChatLuongBT { get; set; }
        public string PPLamSach { get; set; }
        public string XuLyBeMatLH { get; set; }
        public string NhietDoLH { get; set; }
        public string ThoiGianLH { get; set; }
        public string KL1LanMai { get; set; }
        public string ThoiGianMai { get; set; }
        public string LoaiDaMai { get; set; }
        public string TronBot { get; set; }
        public string ChamSon { get; set; }
        public string GanLinhKien { get; set; }
        public string PhuTeflon { get; set; }
        public string BaviaKH { get; set; }
        public string BaviaCaiDat { get; set; }
        public string YeuCauKiemMay { get; set; }
        public string XuLyBeMatKM { get; set; }
        public string NgoaiQuanKM { get; set; }
        public string TyLeNG { get; set; }
        public string TrongLuong1SP { get; set; }
        public string TrongLuongLinhKien { get; set; }
        public int SL1boc { get; set; }
        public string KichThuocBoc { get; set; }
        public int SL1hop { get; set; }
        public string KichThuocThung { get; set; }
        public int SL1thung { get; set; }
        public string PPDongBoc { get; set; }
        public string PPDongHoi { get; set; }
        public string GhiChuKhacDG { get; set; }
        public string KichThuoc { get; set; }
        public string NgoaiQuan { get; set; }
        public string DongGoi { get; set; }
        public string Khac { get; set; }
        public string GhiChu { get; set; }
    }
}
