using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ESSONS_MIS_2020_App.Models
{
    public class QuyTrinhModel
    {
        public string SoChungTu { get; set; }
        public string NgayDuyet { get; set; }
        public string NgayPhatHanh { get; set; }
        public string Noi { get; set; }
        public string CodeKH { get; set; }
        public string CodeSP { get; set; }
        public string TenQU { get; set; }
        public string MaKhuonTW { get; set; }
        public string QuyCachKH { get; set; }
        public string QuyCachEssons { get; set; }
        public string ChatKeo { get; set; }
        public string Mau { get; set; }
        public string MaKeo { get; set; }
        public string SoLoKhuonKH { get; set; }
        public string CoRutTheoDonKhuon { get; set; }
        public string UocTinhKLSP { get; set; }
        public string ThoiGianHoanTat1k { get; set; }
        public string LoaiKhuonMau { get; set; }
        public string NgayGiaoMau { get; set; }
        public string GhiChuKHSX { get; set; }
        public string NgayPheDuyetMua { get; set; }
        public string LoaiThepKhuon { get; set; }
        public string KichThuocKhuon { get; set; }
        public string SoTam { get; set; }
        public string CoRutThucTe { get; set; }
        public string BLBNHCDK { get; set; }
        public string BocTach { get; set; }
        public string NgaySXKhuon { get; set; }
        public string NgayHoanThanhDuKien { get; set; }
        public string NgayHoanThanh { get; set; }
        public string RacBot { get; set; }
        public string TronHoaChat { get; set; }
        public string TongThoiGianTronCan { get; set; }
        public string CatSoiEpDun { get; set; }
        public string DoDay { get; set; }
        public string ChieuDaiMin { get; set; }
        public string ChieuDaiMax { get; set; }
        public string TLSoiMin { get; set; }
        public string TLSoiMax { get; set; }
        public string SoSoi { get; set; }
        public string DoDay2 { get; set; }
        public string ChieuDaiMin2 { get; set; }
        public string ChieuDaiMax2 { get; set; }
        public string TLSoiMin2 { get; set; }
        public string TLSoiMax2 { get; set; }
        public string SoSoi2 { get; set; }
        public string DoDay3 { get; set; }
        public string ChieuDaiMin3 { get; set; }
        public string ChieuDaiMax3 { get; set; }
        public string TLSoiMin3 { get; set; }
        public string TLSoiMax3 { get; set; }
        public string SoSoi3 { get; set; }
        public string DoDay4 { get; set; }
        public string ChieuDaiMin4 { get; set; }
        public string ChieuDaiMax4 { get; set; }
        public string TLSoiMin4 { get; set; }
        public string TLSoiMax4 { get; set; }
        public string SoSoi4 { get; set; }
        public string DoDay5 { get; set; }
        public string ChieuDaiMin5 { get; set; }
        public string ChieuDaiMax5 { get; set; }
        public string TLSoiMin5 { get; set; }
        public string TLSoiMax5 { get; set; }
        public string SoSoi5 { get; set; }
        public string PPDatKeo { get; set; }
        public string CachDat { get; set; }
        public string SoLoKhuon { get; set; }
        public string SoLoThucLam { get; set; }
        public string Tren5 { get; set; }
        public string Duoi5 { get; set; }
        public string LucEp { get; set; }
        public string SoLanThoatKhi { get; set; }
        public string TongTLSat { get; set; }
        public string KLSPThucTe { get; set; }
        public string ThoiGianLuuHoa { get; set; }
        public string ThoiGianHoanTat { get; set; }
        public string ChatLuongKhuon { get; set; }
        public string RacBotSilicon { get; set; }
        public string PPBocTachKiemTra { get; set; }
        public string DungCuHoTro { get; set; }
        public string ViTriKhuon { get; set; }
        public string VitriBanKeo { get; set; }
        public string SoTamTrenKhuon { get; set; }
        public string NgayHoanThanhKhuon { get; set; }
        public string KichThuocTruocLH { get; set; }
        public string KichThuocSauLH { get; set; }
        public string KichThuocLonTieuChuan { get; set; }
        public string KichThuocNhoTieuChuan { get; set; }
        public string KichThuocKhongDongNhat { get; set; }
        public string PPLamSach { get; set; }
        public string RacBotSiliconLH { get; set; }
        public string LH2NhietDo { get; set; }
        public string LH2ThoiGian { get; set; }
        public string PPBocTach { get; set; }
        public string DungCuBocTach { get; set; }
        public string RacBotSiliconBT { get; set; }
        public string MNThoiGian { get; set; }
        public string MNTocDo { get; set; }
        public string MNKL1LanBan { get; set; }
        public string NNhietDo { get; set; }
        public string NCB { get; set; }
        public string BocTachDTK { get; set; }
        public string BanNito { get; set; }
        public string MaiHang { get; set; }
        public string ThoiGianMai { get; set; }
        public string LoaiDaMai { get; set; }
        public string GanLinhKien { get; set; }
        public string BaviaKH { get; set; }
        public string BaviaCaiDat { get; set; }
        public string KHYCKM { get; set; }
        public string RacBotSiliconKM { get; set; }
        public string KTDungCu { get; set; }
        public string KiemPham { get; set; }
        public string TyLeNG { get; set; }
        public string GhiChuThayDoiBT { get; set; }
        public string RacBotSiliconDG { get; set; }
        public string TrongLuong1SP { get; set; }
        public string TrongLuongLinhKien { get; set; }
        public string SL1boc { get; set; }
        public string KichThuocBoc { get; set; }
        public string SL1hop { get; set; }
        public string KichThuocThung { get; set; }
        public string SL1thung { get; set; }
        public string KichThuoc { get; set; }
        public string NgoaiQuan { get; set; }
        public string DongGoi { get; set; }
        public string Khac { get; set; }
        public string GhiChu { get; set; }
    }
}
